# Generated by Django 5.1.6 on 2025-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='item_type',
            field=models.CharField(choices=[('certification', 'Certification'), ('project', 'Project')], max_length=20, null=True),
        ),
    ]
