# Generated by Django 5.1.6 on 2025-02-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='media/portfolio'),
        ),
    ]
