# Generated by Django 5.1.6 on 2025-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='item_type',
            field=models.CharField(choices=[('certification', 'Certification')], max_length=20, null=True),
        ),
    ]
