# Generated by Django 5.1.6 on 2025-02-22 03:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolioitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='portfolio'),
        ),
    ]
